from __future__ import annotations

from typing import Any, Dict

from app.orchestrator import service


def _pick_idea(conn) -> int:
    cursor = conn.execute("SELECT id FROM ideas ORDER BY id DESC LIMIT 1")
    row = cursor.fetchone()
    if row:
        return int(row[0])
    return service.create_idea(conn, "Default idea", "Autogenerated idea for staging.")


def _create_spec(conn, idea_id: int) -> int:
    content = "Staging spec derived from idea." 
    return service.create_spec(conn, idea_id, content)


def _create_tickets(conn, spec_id: int) -> list[int]:
    tickets = [
        ("Seed ticket", "Create initial scaffolding for the idea."),
        ("Verify budget", "Check limits and readiness gating."),
    ]
    return service.create_tickets(conn, spec_id, tickets)


def _simulate_change_plan(ticket_id: int) -> str:
    return f"Plan changes for ticket {ticket_id}: simulate patch set only."


def staging_healthcheck_gate() -> None:
    status = service.healthcheck()
    if not status.get("db") or not status.get("readiness"):
        raise RuntimeError("Healthcheck gate failed for staging")


def run_once(env: str = "staging") -> Dict[str, Any]:
    if env != "staging":
        raise ValueError("run_once is staging-only")

    conn = service.get_db()
    try:
        service.ensure_schema(conn)
        idea_id = _pick_idea(conn)
        spec_id = _create_spec(conn, idea_id)
        _create_tickets(conn, spec_id)
        ticket_id = service.select_one_ticket(conn, spec_id)
        if ticket_id is None:
            raise RuntimeError("No ticket available")
        change_plan = _simulate_change_plan(ticket_id)
        iteration_id = service.record_iteration(conn, idea_id, spec_id, ticket_id, change_plan)
        service.record_deployment_stub(conn, iteration_id, env)
    finally:
        conn.close()

    staging_healthcheck_gate()
    return {
        "idea_id": idea_id,
        "spec_id": spec_id,
        "ticket_id": ticket_id,
        "iteration_id": iteration_id,
        "status": "recorded",
    }
